import type { AgemonProfile, TrainerProfile } from "../engine/types.js";
import { PALETTE } from "../pixel/palette.js";
import { generateSprite, generateMiniSprite } from "../pixel/sprite-generator.js";
import { getTypeLabel, TYPE_COLORS } from "../engine/type-system.js";

const CARD_WIDTH = 1200;
const CARD_HEIGHT = 630;

/**
 * Render a trainer share card to a Canvas.
 * Returns the canvas for PNG export.
 */
export async function renderTrainerCard(
  trainer: TrainerProfile,
): Promise<Buffer | null> {
  try {
    const { createCanvas } = await import("canvas");
    const canvas = createCanvas(CARD_WIDTH, CARD_HEIGHT);
    const ctx = canvas.getContext("2d");

    // Background
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, CARD_WIDTH, CARD_HEIGHT);

    // Header bar
    ctx.fillStyle = "#e74c3c";
    ctx.fillRect(0, 0, CARD_WIDTH, 80);

    // Title
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 36px monospace";
    ctx.fillText("AGEMON", 40, 52);

    // Trainer info
    ctx.fillStyle = "#1a1a2e";
    ctx.font = "bold 28px monospace";
    ctx.fillText(trainer.name, 40, 140);

    ctx.fillStyle = "#636e72";
    ctx.font = "18px monospace";
    ctx.fillText(
      `Lv.${trainer.level}  |  ${trainer.totalAgemon} Agemon  |  ${trainer.totalMoves} Moves  |  ${trainer.totalEquipment} Equipment`,
      40,
      175,
    );

    // Divider
    ctx.strokeStyle = "#e0e0e8";
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(40, 200);
    ctx.lineTo(CARD_WIDTH - 40, 200);
    ctx.stroke();

    // Mini sprites for each agemon
    const allAgemon = [...trainer.globalAgemon, ...trainer.projectAgemon];
    const spriteScale = 6;
    let xOffset = 40;
    let yOffset = 230;

    for (const agemon of allAgemon.slice(0, 8)) {
      const sprite = generateMiniSprite(agemon);

      // Render mini sprite
      for (const layer of sprite.layers) {
        for (let y = 0; y < layer.pixels.length; y++) {
          for (let x = 0; x < (layer.pixels[y]?.length ?? 0); x++) {
            const colorIdx = layer.pixels[y][x];
            if (colorIdx === 0) continue;
            const color = PALETTE[colorIdx];
            if (!color || color === "transparent") continue;
            ctx.fillStyle = color;
            ctx.fillRect(
              xOffset + x * spriteScale,
              yOffset + y * spriteScale,
              spriteScale,
              spriteScale,
            );
          }
        }
      }

      // Agemon name
      ctx.fillStyle = "#1a1a2e";
      ctx.font = "bold 14px monospace";
      ctx.fillText(
        agemon.displayName,
        xOffset,
        yOffset + sprite.height * spriteScale + 20,
      );

      // Level + type
      ctx.fillStyle = "#636e72";
      ctx.font = "12px monospace";
      const typeStr = agemon.types.map(getTypeLabel).join("/");
      ctx.fillText(
        `Lv.${agemon.level} ${typeStr}`,
        xOffset,
        yOffset + sprite.height * spriteScale + 38,
      );

      xOffset += 130;
      if (xOffset > CARD_WIDTH - 140) {
        xOffset = 40;
        yOffset += sprite.height * spriteScale + 60;
      }
    }

    // Footer
    ctx.fillStyle = "#9e9eae";
    ctx.font = "12px monospace";
    ctx.fillText("Generated by Agemon", 40, CARD_HEIGHT - 20);

    return canvas.toBuffer("image/png");
  } catch {
    return null;
  }
}

/**
 * Render a single Agemon share card to PNG.
 */
export async function renderAgemonCard(
  profile: AgemonProfile,
): Promise<Buffer | null> {
  try {
    const { createCanvas } = await import("canvas");
    const canvas = createCanvas(CARD_WIDTH, CARD_HEIGHT);
    const ctx = canvas.getContext("2d");

    // Background
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, CARD_WIDTH, CARD_HEIGHT);

    // Header bar with type color
    const typeColor = TYPE_COLORS[profile.types[0] ?? "scholar"];
    ctx.fillStyle = typeColor.primary;
    ctx.fillRect(0, 0, CARD_WIDTH, 80);

    // Title
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 36px monospace";
    ctx.fillText("AGEMON", 40, 52);

    // Full sprite
    const sprite = generateSprite(profile);
    const spriteScale = 8;
    const spriteX = 60;
    const spriteY = 120;

    for (const layer of sprite.layers) {
      for (let y = 0; y < layer.pixels.length; y++) {
        for (let x = 0; x < (layer.pixels[y]?.length ?? 0); x++) {
          const colorIdx = layer.pixels[y][x];
          if (colorIdx === 0) continue;
          const color = PALETTE[colorIdx];
          if (!color || color === "transparent") continue;
          ctx.fillStyle = color;
          ctx.fillRect(
            spriteX + x * spriteScale,
            spriteY + y * spriteScale,
            spriteScale,
            spriteScale,
          );
        }
      }
    }

    // Info panel
    const infoX = spriteX + sprite.width * spriteScale + 60;

    ctx.fillStyle = "#1a1a2e";
    ctx.font = "bold 32px monospace";
    ctx.fillText(profile.displayName, infoX, 150);

    ctx.fillStyle = "#636e72";
    ctx.font = "16px monospace";
    ctx.fillText(
      `${profile.source === "command" ? "CMD" : "MCP"} / ${profile.name}`,
      infoX,
      180,
    );

    // Type badges
    let badgeX = infoX;
    ctx.font = "bold 14px monospace";
    for (const type of profile.types) {
      const tc = TYPE_COLORS[type];
      ctx.fillStyle = tc.primary;
      ctx.fillRect(badgeX, 195, 80, 24);
      ctx.fillStyle = "#ffffff";
      ctx.fillText(getTypeLabel(type), badgeX + 8, 213);
      badgeX += 90;
    }

    // Stats
    const statY = 250;
    const statNames: (keyof typeof profile.stats)[] = [
      "knowledge",
      "arsenal",
      "reflex",
      "mastery",
      "guard",
      "synergy",
    ];

    for (let i = 0; i < statNames.length; i++) {
      const name = statNames[i];
      const value = profile.stats[name];
      const y = statY + i * 30;

      ctx.fillStyle = "#636e72";
      ctx.font = "14px monospace";
      ctx.fillText(name.slice(0, 3).toUpperCase(), infoX, y + 14);

      // Bar background
      ctx.fillStyle = "#e0e0e8";
      ctx.fillRect(infoX + 50, y, 200, 16);

      // Bar fill
      ctx.fillStyle = typeColor.primary;
      ctx.fillRect(infoX + 50, y, value * 2, 16);

      ctx.fillStyle = "#1a1a2e";
      ctx.font = "12px monospace";
      ctx.fillText(String(Math.round(value)), infoX + 260, y + 13);
    }

    // Level / XP
    ctx.fillStyle = "#1a1a2e";
    ctx.font = "bold 20px monospace";
    ctx.fillText(
      `Lv.${profile.level}  ${profile.evolution.stage} (${profile.evolution.title})`,
      infoX,
      statY + 210,
    );
    ctx.fillStyle = "#636e72";
    ctx.font = "14px monospace";
    ctx.fillText(
      `XP: ${profile.xp}/${profile.evolution.nextLevelXp}  |  Moves: ${profile.moves.length}`,
      infoX,
      statY + 240,
    );

    // Footer
    ctx.fillStyle = "#9e9eae";
    ctx.font = "12px monospace";
    ctx.fillText("Generated by Agemon", 40, CARD_HEIGHT - 20);

    return canvas.toBuffer("image/png");
  } catch {
    return null;
  }
}
